name: Astronomer CI - Create preview Deployment

on:
  create:
    branches:
    - "**"

env:
  ## Set your Workspace API key token as a GitHub secret
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Create preview Deployment
      uses: astronomer/deploy-action@v0.2
      with:
        action: create-deployment-preview
        deployment-id: cljptd9jm817514jbz31x6u0su5
